library glide2x_wrapper;

{$mode objfpc}{$H+}

uses
  funcwrap;

exports
  grAADrawLine  Name '_grAADrawLine@8',
  grAADrawPoint  Name '_grAADrawPoint@4',
  grAADrawPolygon  Name '_grAADrawPolygon@12',
  grAADrawPolygonVertexList  Name '_grAADrawPolygonVertexList@8',
  grAADrawTriangle  Name '_grAADrawTriangle@24',
  grAlphaBlendFunction  Name '_grAlphaBlendFunction@16',
  grAlphaCombine  Name '_grAlphaCombine@20',
  grAlphaControlsITRGBLighting  Name '_grAlphaControlsITRGBLighting@4',
  grAlphaTestFunction  Name '_grAlphaTestFunction@4',
  grAlphaTestReferenceValue  Name '_grAlphaTestReferenceValue@4',
  grBufferClear  Name '_grBufferClear@12',
  grBufferNumPending  Name '_grBufferNumPending@0',
  grBufferSwap  Name '_grBufferSwap@4',
  grCheckForRoom  Name '_grCheckForRoom@4',
  grChromakeyMode  Name '_grChromakeyMode@4',
  grChromakeyValue  Name '_grChromakeyValue@4',
  grClipWindow  Name '_grClipWindow@16',
  grColorCombine  Name '_grColorCombine@20',
  grColorMask  Name '_grColorMask@8',
  grConstantColorValue4  Name '_grConstantColorValue4@16',
  grConstantColorValue  Name '_grConstantColorValue@4',
  grCullMode  Name '_grCullMode@4',
  grDepthBiasLevel  Name '_grDepthBiasLevel@4',
  grDepthBufferFunction  Name '_grDepthBufferFunction@4',
  grDepthBufferMode  Name '_grDepthBufferMode@4',
  grDepthMask  Name '_grDepthMask@4',
  grDisableAllEffects  Name '_grDisableAllEffects@0',
  grDitherMode  Name '_grDitherMode@4',
  grDrawLine  Name '_grDrawLine@8',
  grDrawPlanarPolygon  Name '_grDrawPlanarPolygon@12',
  grDrawPlanarPolygonVertexList  Name '_grDrawPlanarPolygonVertexList@8',
  grDrawPoint  Name '_grDrawPoint@4',
  grDrawPolygon  Name '_grDrawPolygon@12',
  grDrawPolygonVertexList  Name '_grDrawPolygonVertexList@8',
  grDrawTriangle  Name '_grDrawTriangle@12',
  grErrorSetCallback  Name '_grErrorSetCallback@4',
  grFogColorValue  Name '_grFogColorValue@4',
  grFogMode  Name '_grFogMode@4',
  grFogTable  Name '_grFogTable@4',
  grGammaCorrectionValue  Name '_grGammaCorrectionValue@4',
  grGlideGetState  Name '_grGlideGetState@4',
  grGlideGetVersion  Name '_grGlideGetVersion@4',
  grGlideInit  Name '_grGlideInit@0',
  grGlideSetState  Name '_grGlideSetState@4',
  grGlideShamelessPlug  Name '_grGlideShamelessPlug@4',
  grGlideShutdown  Name '_grGlideShutdown@0',
  grHints  Name '_grHints@8',
  grLfbConstantAlpha  Name '_grLfbConstantAlpha@4',
  grLfbConstantDepth  Name '_grLfbConstantDepth@4',
  grLfbLock  Name '_grLfbLock@24',
  grLfbReadRegion  Name '_grLfbReadRegion@28',
  grLfbUnlock  Name '_grLfbUnlock@8',
  grLfbWriteColorFormat  Name '_grLfbWriteColorFormat@4',
  grLfbWriteColorSwizzle  Name '_grLfbWriteColorSwizzle@8',
  grLfbWriteRegion  Name '_grLfbWriteRegion@32',
  grRenderBuffer  Name '_grRenderBuffer@4',
  grResetTriStats  Name '_grResetTriStats@0',
  grSplash  Name '_grSplash@20',
  grSstControl  Name '_grSstControl@4',
  grSstIdle  Name '_grSstIdle@0',
  grSstIsBusy  Name '_grSstIsBusy@0',
  grSstOrigin  Name '_grSstOrigin@4',
  grSstPerfStats  Name '_grSstPerfStats@4',
  grSstQueryBoards  Name '_grSstQueryBoards@4',
  grSstQueryHardware  Name '_grSstQueryHardware@4',
  grSstResetPerfStats  Name '_grSstResetPerfStats@0',
  grSstScreenHeight  Name '_grSstScreenHeight@0',
  grSstScreenWidth  Name '_grSstScreenWidth@0',
  grSstSelect  Name '_grSstSelect@4',
  grSstStatus  Name '_grSstStatus@0',
  grSstVRetraceOn  Name '_grSstVRetraceOn@0',
  grSstVideoLine  Name '_grSstVideoLine@0',
  grSstWinClose  Name '_grSstWinClose@0',
  grSstWinOpen  Name '_grSstWinOpen@28',
  grTexCalcMemRequired  Name '_grTexCalcMemRequired@16',
  grTexClampMode  Name '_grTexClampMode@12',
  grTexCombine  Name '_grTexCombine@28',
  grTexCombineFunction  Name '_grTexCombineFunction@8',
  grTexDetailControl  Name '_grTexDetailControl@16',
  grTexDownloadMipMap  Name '_grTexDownloadMipMap@16',
  grTexDownloadMipMapLevel  Name '_grTexDownloadMipMapLevel@32',
  grTexDownloadMipMapLevelPartial  Name '_grTexDownloadMipMapLevelPartial@40',
  grTexDownloadTable  Name '_grTexDownloadTable@12',
  grTexDownloadTablePartial  Name '_grTexDownloadTablePartial@20',
  grTexFilterMode  Name '_grTexFilterMode@12',
  grTexLodBiasValue  Name '_grTexLodBiasValue@8',
  grTexMaxAddress  Name '_grTexMaxAddress@4',
  grTexMinAddress  Name '_grTexMinAddress@4',
  grTexMipMapMode  Name '_grTexMipMapMode@12',
  grTexMultibase  Name '_grTexMultibase@8',
  grTexMultibaseAddress  Name '_grTexMultibaseAddress@20',
  grTexNCCTable  Name '_grTexNCCTable@8',
  grTexSource  Name '_grTexSource@16',
  grTexTextureMemRequired  Name '_grTexTextureMemRequired@8',
  grTriStats  Name '_grTriStats@8',

  //utility
  gu3dfGetInfo Name '_gu3dfGetInfo@8',
  gu3dfLoad Name '_gu3dfLoad@8',
  guAADrawTriangleWithClip Name '_guAADrawTriangleWithClip@12',
  guAlphaSource Name '_guAlphaSource@4',
  guColorCombineFunction Name '_guColorCombineFunction@4',
  guDrawTriangleWithClip Name '_guDrawTriangleWithClip@12',
  guFogGenerateExp2 Name '_guFogGenerateExp2@8',
  guFogGenerateExp Name '_guFogGenerateExp@8',
  guFogGenerateLinear Name '_guFogGenerateLinear@12',
  guFogTableIndexToW Name '_guFogTableIndexToW@4',
  guTexAllocateMemory Name '_guTexAllocateMemory@60',
  guTexChangeAttributes Name '_guTexChangeAttributes@48',
  guTexCombineFunction Name '_guTexCombineFunction@8',
  guTexDownloadMipMap Name '_guTexDownloadMipMap@12',
  guTexDownloadMipMapLevel Name '_guTexDownloadMipMapLevel@12',
  guTexGetCurrentMipMap Name '_guTexGetCurrentMipMap@4',
  guTexGetMipMapInfo Name '_guTexGetMipMapInfo@4',
  guTexMemQueryAvail Name '_guTexMemQueryAvail@4',
  guTexMemReset Name '_guTexMemReset@0',
  guTexSource Name '_guTexSource@4',

  { functions exported from glide2x (FX_ENTRY) but not mentioned in ref. manual nor prog. guide }
  guDrawPolygonVertexListWithClip Name '_guDrawPolygonVertexListWithClip@8',
  guEncodeRLE16  Name '_guEncodeRLE16@16',
  guEndianSwapBytes  Name '_guEndianSwapBytes@4',
  guEndianSwapWords Name '_guEndianSwapWords@4',
  guTexCreateColorMipMap Name '_guTexCreateColorMipMap@0',
  ConvertAndDownloadRle  Name '_ConvertAndDownloadRle@64';

initialization
  SetGlideLib('..\glide2x.dll');

finalization
  Unload;

end.

